from fastapi import APIRouter, HTTPException

from models.identity_models import (
    SecureHttpsConnectionDemoRequest,
    SecureHttpsConnectionDemoResponse,
)
from services.https_demo_service import simulate_secure_https_connection


router = APIRouter(
    prefix="/intranet/demo",
    tags=["Intranet HTTPS Demo"],
)


@router.get("/secure-https-connection/info")
def secure_https_connection_info():
    return {
        "title": "Secure Internal HTTPS Connection Demo",
        "purpose": (
            "Simulate the application-data protection phase of an internal HTTPS "
            "connection after the corporate client has validated the intranet "
            "server certificate."
        ),
        "scope": {
            "models": "server-authenticated HTTPS inside a Private Trust environment",
            "does_not_model": [
                "a production TLS stack",
                "a real TLS handshake",
                "mutual TLS",
                "client certificate authentication",
                "ML-KEM/PQC key exchange",
            ],
        },
        "pqc_usage": {
            "used_for": (
                "PQC is used in the X.509 server certificate generated by the "
                "internal CA and validated before establishing the simulated session."
            ),
            "not_used_for": (
                "This endpoint does not use ML-KEM or any PQC KEM to establish "
                "the session key."
            ),
        },
        "session_model": {
            "identity_layer": "PQC X.509 server certificate validation with OpenSSL",
            "channel_layer": "simulated AES-256-GCM protected application-data phase",
            "client_authenticated": False,
            "server_authenticated": True,
        },
        "why_no_pqc_key_exchange_here": (
            "api-intranet is intentionally limited to the regular HTTPS case where "
            "the client validates the server identity. PQC key establishment and "
            "mutual authentication are left for more advanced scenarios such as "
            "api-mTLS, so that the APIs remain conceptually distinct."
        ),
        "measurements": [
            "identity_verification_phase_ms",
            "session_key_generation_ms",
            "aes_gcm_encryption_ms",
            "aes_gcm_decryption_ms",
            "total_secure_https_demo_ms",
        ],
    }


@router.post(
    "/secure-https-connection",
    response_model=SecureHttpsConnectionDemoResponse,
)
def demo_secure_https_connection(request: SecureHttpsConnectionDemoRequest):
    try:
        return simulate_secure_https_connection(request)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))