services:
  pqc-base:
    build:
      context: .
      dockerfile: pqc-base/Dockerfile
    ports:
      - "8001:8000"

  api-merkle:
    build:
      context: .
      dockerfile: api-merkle/Dockerfile
    ports:
      - "8002:8000"

  api-intranet:
    build:
      context: .
      dockerfile: api-intranet/Dockerfile
    ports:
      - "8003:8000"    

  api-interna:
    build:
      context: .
      dockerfile: api-interna/Dockerfile
    ports:
      - "8004:8000"    