from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class EncryptedRequestFromClient(BaseModel):
    """
    Encrypted request received from the client service.

    The client sends:
    - its certificate;
    - the handshake session identifier;
    - the ML-KEM ciphertext;
    - the AES-GCM encrypted payload.
    """

    session_id: str = Field(
        description="Handshake session identifier previously created by the server.",
    )

    client_certificate_pem: str = Field(
        description="PEM-encoded certificate of the client service.",
    )

    kem_algorithm: str = Field(
        default="ML-KEM-768",
        description="KEM algorithm used for session establishment.",
    )

    kem_ciphertext_b64: str = Field(
        description="Base64-encoded ML-KEM ciphertext generated by the client.",
    )

    encryption_algorithm: str = Field(
        default="AES-256-GCM",
        description="Authenticated encryption algorithm used for the payload.",
    )

    nonce_b64: str = Field(
        description="Base64-encoded AES-GCM nonce for the encrypted request.",
    )

    aad_b64: str = Field(
        description="Base64-encoded additional authenticated data for the encrypted request.",
    )

    encrypted_payload_b64: str = Field(
        description="Base64-encoded AES-GCM encrypted request payload.",
    )

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Non-sensitive request metadata used for traceability.",
    )


class SecureEndpointResponse(BaseModel):
    secure_request_processed: bool
    request_decrypted_by_server: bool
    server_verified_client_certificate: bool

    response_encrypted_by_server: bool = False

    reason: str

    decrypted_payload: Optional[Dict[str, Any]] = None

    encrypted_response_b64: Optional[str] = None
    response_nonce_b64: Optional[str] = None
    response_aad_b64: Optional[str] = None
    response_metadata: Dict[str, Any] = Field(default_factory=dict)

    client_certificate_verification: Dict[str, Any]
    kem: Dict[str, Any]
    encryption: Dict[str, Any]

    server_service: Dict[str, Any]

    steps: List[str]
    measurements: Dict[str, float]